### ISSUE TITLE
Provide arguments to cage shell label?

### ISSUE THREAD

**Issue by neezer** [faradayio/cage#107]
I'd love to be able to set my default shell for my PostgreSQL container to

```yml
services:
  pg:
    labels:
      io.fdy.cage.shell: "psql -U postgres"
```

... but it appears cage treats that string as the name of the executable. It works for my redis container because I don't need to provide arguments. Not providing arguments means `psql` tries to login as `root` instead of `postgres` which yields an authentication failure. I've also tried setting the environment variables `POSTGRES_USER` and `PGPASSWORD` but the cage shell command seems to ignore those.
