### ISSUE TITLE
Implement `extends`

### ISSUE THREAD

**Issue by emk** [faradayio/cage#58]
At the moment, `cage` really doesn't have any particularly good support for `extends`.

We could support this as follows:

```yaml
extends:
  file: "templates/webapp.yml"
  service: "webapp"
```

Optionally, we could also have support for overriding templates:

- `pods/templates/webapp.yml`
- `pods/targets/$TARGET/templates/webapp.yml`

The trick would be to merge these two files _before_ we use them as input to the `extends`. This would allow us to handle cases where we use one `image` in development, and a different `image` in production.
