### ISSUE TITLE
`cage test <service>` is an antipattern

### ISSUE THREAD

**Issue by dkastner** [faradayio/cage#65]
We created `cage test <service>` for our own needs, but if we want cage to be an opinionated framework for multi-container apps that encourages best practices, we need to make this functionality more of a customization than an integral/recommended feature.

The recommended setup ought to be that each service can run its own unit and integration tests independently from the rest of the other services.

Of course, you'd still want a test target that can run acceptance tests and any focused integration tests between a few services. But this test mode should not be relied on for independent service unit tests.

Example: We have a rails app called `web`. Inside there is a docker-compose.yml:

```yaml
test:
  command: rake
  build: .
  volumes:
    - ./:/app
  environment:
    RAILS_ENV: test
    DATABASE_URL: postgres://postgres@db/web_test
  depends_on:
    - db

db:
  image: postgresql

prepare:
  extends: test
  command: rake db:setup
```

And you can run tests with `docker-compose run prepare` and then `docker-compose run test` or individual RSpec tests with `docker-compose run test rspec spec/foo_spec.rb --fail-fast`

The docker-compose.yml can be created by a future plugin system for generating apps.
