### ISSUE TITLE
'invalid image' when trying to use a private registry image

### ISSUE THREAD

**Issue by camjackson** [faradayio/cage#68]
I'm getting an error like this (data somewhat sanitised):

```
Error: could not read 'pods/my-pod.yml'
error reading file 'pods/my-pod.yml'
invalid image 'my-private-registry:5000/my-org-name/my-app-name'
```

Config snippet:
```
# pods/my-pod.yml
services:
  my-app-name:
    image: 'my-private-registry:5000/my-org-name/my-app-name'
```

It's definitely a valid image name though. I can do `docker run my-private-registry:5000/my-org-name/my-app-name` and it works just fine. Looks like a case of overly-strict image name validation?

If that's the case, it seems that Cage is not compatible with private docker registries. Which would suck, because so far I'm really loving what Cage can do!
