### ISSUE TITLE
docker-compose.yml `version` is not preserved

### ISSUE THREAD

**Issue by dkastner** [faradayio/cage#89]
Example project:

```
.
└── pods
   ├── db.yml
```

```
# in pods/db.yml
version: "2.1"
services:
  db:
    healthcheck:
      test: ["CMD", "true"]
```

When I run `cage up` I get:

```
ERROR: The Compose file '/foo/.cage/pods/db.yml' is invalid because:
Unsupported config option for services.db: 'healthcheck'
Error: error running 'docker-compose -p foo -f /foo/.cage/pods/db.yml up -d'
```

Looking at `/foo/.cage/pods/db.yml`, I see that it's configured with `version: "2"`. 

**Expected**: `/foo/.cage/pods/db.yml` should have `version: "2.1"`

My hunch is that cage is creating an empty `compose_yml::v2::File` which gets a default version of `"2"`: https://github.com/emk/compose_yml/blob/b660f32fd4579a7e90526b51e0b97456b0b23c3e/src/v2/file.rs#L102
