### ISSUE TITLE
`cage up` does not work with URL as build context

### ISSUE THREAD

**Issue by andrewsardone** [faradayio/cage#90]
Hi there! 👋 `cage` looks like a nice tool, and I'm excited to try it out on a project, but I'm hitting  snag.

I created a service within `pods/frontend.yml` that uses [a `build` context](https://docs.docker.com/compose/compose-file/#build) of a git repo URL ([source code](https://github.com/andrewsardone/example-cage-project-with-build-context/blob/82dea513d73bf89d6d2ec54398cbff911225fb55/pods/frontend.yml#L7)). I can run `cargo build` to build the image, and things look good.

**The problem is with running `cage up`.** I see the following error message:

```
❯ cage up
WARNING: docker-compose.yml file validation disabled until valico is updated (from compose_yml::v2::validate)
WARNING: docker-compose.yml file validation disabled until valico is updated (from compose_yml::v2::validate)
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
Error: error running 'docker-compose -p examplecageprojectwithbuildcontext -f /Users/andrew/source/andrewsardone/example-cage-project-with-build-context/.cage/pods/frontend.yml up -d'
```

Inspecting my **generated docker-compose file** within the `.cage` directory, I see **it's missing a `build` context**:

```
❯ cat /Users/andrew/source/andrewsardone/example-cage-project-with-build-context/.cage/pods/frontend.yml
---
version: "2"
services:
  web:
    environment:
      DATABASE_URL: "postgres://postgres@db:5432/example-cage-project-with-build-context_development"
      GLOBAL_PASSWORD: magic
      PROJECT_NAME: "example-cage-project-with-build-context"
      RACK_ENV: development
      RAILS_ENV: development
      SOME_PASSWORD: secret
    labels:
      io.fdy.cage.pod: frontend
      io.fdy.cage.shell: bash
      io.fdy.cage.srcdir: /usr/src/app
      io.fdy.cage.target: development
      io.fdy.cage.test: bundle exec rake
    ports:
      - "3000:3000" 
```

([Extended description in source code's README](https://github.com/andrewsardone/example-cage-project-with-build-context#cage-build-works)).

---

Is there something I'm missing? Am I using `cage` improperly? If not, any idea of the source of the bug?

Thanks!
