### ISSUE TITLE
Can't use ipv4_address in backend.yml

### ISSUE THREAD

**Issue by chenfwww** [faradayio/cage#92]
I want to use ipv4-address field in docker-compose file, and this field is supported by docker-compose.yml version 2. 
However, when I run `cage up`, I got this error:
> services.paas.networks.net: unknown field `ipv4_address`, expected `aliases` at line 28 column 9

Below is my backend.yml:
```
service
  node2: 
    image: "paas/node"
    build: .
    networks: 
      net:
        ipv4_address: 172.24.0.2
  
networks: 
  net:
    ipam:
      config:
        - subnet: 172.24.0.0/24
```
